# Generated by Django 4.1 on 2023-03-15 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthenticationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
                ('userMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.usermeta')),
            ],
        ),
        migrations.CreateModel(
            name='SessionMeta',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.usermeta')),
            ],
        ),
    ]
