# Generated by Django 4.1 on 2023-04-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomePage', '0006_alter_userprogress_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('userMeta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmeta_usermeta1', to='HomePage.usermeta')),
                ('userMeta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmeta_usermeta2', to='HomePage.usermeta')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(editable=False, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatPage.chatmeta')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomePage.usermeta')),
            ],
        ),
    ]
