# Generated by Django 4.1 on 2023-03-18 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingauthentication',
            name='id',
        ),
        migrations.AddField(
            model_name='waitingauthentication',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
