# Generated by Django 4.1 on 2023-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0002_userprogress_usereconomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereconomy',
            name='amount_of_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usereconomy',
            name='amount_of_exp',
            field=models.IntegerField(default=0),
        ),
    ]
