# Generated by Django 4.1 on 2023-03-18 17:22

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_languagemeta_document_path'),
        ('ProfilePage', '0003_alter_usereconomy_amount_of_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('travelling', 'Travelling'), ('reading', 'Reading'), ('gaming', 'Gaming')], max_length=25, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language_learning',
            field=models.ManyToManyField(null=True, related_name='learning_profiles', to='HomePage.languagemeta'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='native_language',
            field=models.ManyToManyField(null=True, related_name='native_profiles', to='HomePage.languagemeta'),
        ),
    ]
