# Generated by Django 4.1 on 2023-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
