# Generated by Django 4.1 on 2023-03-18 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_alter_usermeta_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMeta',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=19)),
                ('document_path', models.FileField(upload_to='language_documents/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
