# Generated by Django 4.1 on 2023-03-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_languagemeta_document_path'),
        ('ProfilePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=1000)),
                ('languageMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.languagemeta')),
                ('userMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.usermeta')),
            ],
        ),
        migrations.CreateModel(
            name='UserEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_coins', models.IntegerField()),
                ('amount_of_exp', models.IntegerField()),
                ('userMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.usermeta')),
            ],
        ),
    ]
