# Generated by Django 4.1 on 2023-03-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0008_remove_userprofile_native_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
