# Generated by Django 4.1 on 2023-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_userprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='progress',
            field=models.JSONField(null=True),
        ),
    ]
